### ISSUE TITLE
Tuning for POWER9

### ISSUE THREAD

**Issue by madscientist159** [madscientist159/xmrig#2]
Similar to #1 I'm opening a thread to track general tuning for POWER9.

After extensive tuning work, we have an internal version of xmrig that will do 85% of CNv8 on the POWER9 10 core and up CPUs at the same power usage as CNv7.  Allowing power usage to climb by ~20% (basic firmware power table modifications required) puts the hashrate at parity with CNv7, which seems to match the overall tuning results seen on the GPU side.

Since this was a tremendous amount of work, **I'm going to approach release a bit differently than normal**.  I'll be watching the donation address listed on the main page of this repository, and if even a few people are interested enough to support the tuning work on POWER via reasonable donations I'll post the tuned code + some notes on why and where POWER acts differently than x86.

Here are some numbers for your evaluation, same power use as CNv7 (no overclocking / power table changes):
```Dual 18 core system: 2858H/s```
```Dual 22 core system: 3500H/s```

**Comment by cryptoeight** [comment]
@madscientist159 as a appreciation of your effort so far i send you 1 xmr to your wallet and also have the 5% donation active in the running rigs.

Keep going with your good job......

**Comment by madscientist159** [comment]
@cryptoeight Thank you!  Much appreciated :+1: 

FWIW I actually messed up the donation code the first time around, it won't connect.  The current version in this repository fixes that issue.

**Comment by nioroso-x3** [comment]
From my experience, don't expect more than 10 xmr total donations.
I did the port just for the challenge, but if you really tuned your miner to get that fast, I'd release it as closed source with forced dev fee.

**Comment by madscientist159** [comment]
@nioroso-x3 No worries, I'm not looking for much :smile:  Just enough to at least be able to go do something fun with friends, etc. after staring at perf logs and ppc64 assembly for 18 hours a day. :wink: 

xmrig is GPL licensed so a closed binary was never an option.  Besides, I'd rather give people the choice to give a little something to support what they want to see vs. forcing payments on them.

**Comment by madscientist159** [comment]
I've gone ahead and pushed the final version of the miner to this repo.  With the bottom having fallen out of the markets, seemingly for the long term, I'm probably not going to work on this any more. :disappointed:  It's not profitable to mine at this point even if you already have the hardware -- cost of electricity is high enough even in cheaper power markets to outpace any income from mining.

So, here's the miner for anyone on free / solar / etc. power....
